DROP TABLE IF EXISTS EMPLOYEES_LAST_15_MIN;
DROP TABLE IF EXISTS EMPLOYEES_PART;
CREATE TABLE EMPLOYEES_LAST_15_MIN 
    ( 
     EMPLOYEE_ID NUMERIC (6)  NOT NULL , 
     FIRST_NAME varchar (20 ) , 
     LAST_NAME varchar (25 )  NOT NULL , 
     EMAIL varchar (25 )  NOT NULL , 
     PHONE_NUMBER varchar (20 ) , 
     HIRE_DATE DATE  NOT NULL , 
     JOB_ID varchar (10 )  NOT NULL , 
     SALARY NUMERIC (8,2) , 
     COMMISSION_PCT NUMERIC (2,2) , 
     MANAGER_ID NUMERIC (6) , 
     DEPARTMENT_ID NUMERIC (4) 
    )  
;
CREATE TABLE EMPLOYEES_PART
(
     EMPLOYEE_ID NUMERIC (6)  NOT NULL , 
     FIRST_NAME character varying (20 ) , 
     LAST_NAME character varying (25 )  NOT NULL , 
     EMAIL character varying (25 )  NOT NULL , 
     PHONE_NUMBER character varying (20 ) , 
     HIRE_DATE DATE  NOT NULL , 
     JOB_ID character varying (10 )  NOT NULL , 
     SALARY NUMERIC (8,2) , 
     COMMISSION_PCT NUMERIC (2,2) , 
     MANAGER_ID NUMERIC (6) , 
     DEPARTMENT_ID NUMERIC (4)
) PARTITION BY RANGE (HIRE_DATE);

alter table EMPLOYEES_PART set storage extended;

CREATE TABLE EMPLOYEES_PART_2001 PARTITION OF EMPLOYEES_PART FOR VALUES FROM ('2001-01-01') TO ('2001-12-31');
CREATE TABLE EMPLOYEES_PART_2002 PARTITION OF EMPLOYEES_PART FOR VALUES FROM ('2002-01-01') TO ('2002-12-31');
CREATE TABLE EMPLOYEES_PART_2003 PARTITION OF EMPLOYEES_PART FOR VALUES FROM ('2003-01-01') TO ('2003-12-31');
CREATE TABLE EMPLOYEES_PART_2004 PARTITION OF EMPLOYEES_PART FOR VALUES FROM ('2004-01-01') TO ('2004-12-31');
CREATE TABLE EMPLOYEES_PART_2005 PARTITION OF EMPLOYEES_PART FOR VALUES FROM ('2005-01-01') TO ('2005-12-31');
CREATE TABLE EMPLOYEES_PART_2006 PARTITION OF EMPLOYEES_PART FOR VALUES FROM ('2006-01-01') TO ('2006-12-31');
CREATE TABLE EMPLOYEES_PART_2007 PARTITION OF EMPLOYEES_PART FOR VALUES FROM ('2007-01-01') TO ('2007-12-31');
CREATE TABLE EMPLOYEES_PART_2008 PARTITION OF EMPLOYEES_PART FOR VALUES FROM ('2008-01-01') TO ('2008-12-31');


insert into EMPLOYEES_PART select * from EMPLOYEES ;

select * from EMPLOYEES_PART;

SELECT 
distinct 'CREATE TABLE EMPLOYEES_PART_'||extract(year from HIRE_DATE)||' PARTITION OF EMPLOYEES_PART FOR VALUES FROM ('||extract(year from HIRE_DATE)||'-01-01) TO ('||extract(year from HIRE_DATE)||'-12-31);'
--,* 
FROM EMPLOYEES;